# Logging configuration
logging:
  wandb:
    enabled: false
    project: falcon_examples
    group: 02_bimodal_regular
    dir: ${run_dir}
  local:
    enabled: true
    dir: ${paths.graph}

# Directory configuration
paths:
  import: "./src"
  graph: ${run_dir}/graph
  samples: ${run_dir}/samples

# Training buffer parameters
buffer:
  min_samples: 2048
  max_samples: 8192
  validation_samples: 256
  simulate_count: 512
  simulate_when_full: false
  simulate_interval: 15

# Graph definition using declarative YAML
graph:
  z:
    evidence: [x]
    simulator: 
      _target_: falcon.priors.Hypercube
      priors: 
        - ['uniform', -10000.0, 10000.0]
        - ['uniform', -10000.0, 10000.0]
        - ['uniform', -10000.0, 10000.0]
        - ['uniform', -10000.0, 10000.0]
        - ['uniform', -10000.0, 10000.0]
        - ['uniform', -10000.0, 10000.0]
        - ['uniform', -10000.0, 10000.0]
        - ['uniform', -10000.0, 10000.0]
        - ['uniform', -10000.0, 10000.0]
        - ['uniform', -10000.0, 10000.0]
    estimator:
      _target_: falcon.estimators.Flow
      loop:
        max_epochs: 300
        batch_size: 128
        early_stop_patience: 32
      network:
        net_type: nsf  # zuko_gf, maf, nice, sospf, naf, gf
        theta_norm: true
        norm_momentum: 0.003
        use_log_update: true
        adaptive_momentum: false
      embedding:
        _target_: model.E
        _input_: [x]
      optimizer:
        lr: 0.01
        lr_decay_factor: 0.5
        scheduler_patience: 16
      inference:
        gamma: 0.5
        discard_samples: true
        log_ratio_threshold: -20
        sample_reference_posterior: false
        use_best_models_during_inference: true
    ray:
      num_gpus: 1
  
  m:
    parents: [z]
    simulator: model.Signal

  n:
    simulator: model.Noise

  x:
    parents: [m, n]
    simulator: model.Add
    observed: "./data/x_obs_10dim.npy"

sample:
  prior:
    n: 1000
  proposal:
    n: 1000
  posterior:
    n: 1000
